/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    'business-sectors': BusinessSector;
    'sector-categories': SectorCategory;
    'sector-license-requirements': SectorLicenseRequirement;
    'sector-competency-certificates': SectorCompetencyCertificate;
    'sector-approvals': SectorApproval;
    'sector-costs': SectorCost;
    'sector-steps': SectorStep;
    'sector-documents': SectorDocument;
    reports: Report;
    experts: Expert;
    'market-research': MarketResearch;
    pages: Page;
    'blog-posts': BlogPost;
    media: Media;
    'saved-sectors': SavedSector;
    'saved-reports': SavedReport;
    'user-checklists': UserChecklist;
    'report-requests': ReportRequest;
    'news-sources': NewsSource;
    'planning-canvases': PlanningCanvase;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'business-sectors': BusinessSectorsSelect<false> | BusinessSectorsSelect<true>;
    'sector-categories': SectorCategoriesSelect<false> | SectorCategoriesSelect<true>;
    'sector-license-requirements': SectorLicenseRequirementsSelect<false> | SectorLicenseRequirementsSelect<true>;
    'sector-competency-certificates': SectorCompetencyCertificatesSelect<false> | SectorCompetencyCertificatesSelect<true>;
    'sector-approvals': SectorApprovalsSelect<false> | SectorApprovalsSelect<true>;
    'sector-costs': SectorCostsSelect<false> | SectorCostsSelect<true>;
    'sector-steps': SectorStepsSelect<false> | SectorStepsSelect<true>;
    'sector-documents': SectorDocumentsSelect<false> | SectorDocumentsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    experts: ExpertsSelect<false> | ExpertsSelect<true>;
    'market-research': MarketResearchSelect<false> | MarketResearchSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'saved-sectors': SavedSectorsSelect<false> | SavedSectorsSelect<true>;
    'saved-reports': SavedReportsSelect<false> | SavedReportsSelect<true>;
    'user-checklists': UserChecklistsSelect<false> | UserChecklistsSelect<true>;
    'report-requests': ReportRequestsSelect<false> | ReportRequestsSelect<true>;
    'news-sources': NewsSourcesSelect<false> | NewsSourcesSelect<true>;
    'planning-canvases': PlanningCanvasesSelect<false> | PlanningCanvasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'homepage-content': HomepageContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-content': HomepageContentSelect<false> | HomepageContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Payload CMS admin users (separate from app users in Better Auth).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  role: 'super_admin' | 'editor' | 'reviewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * Primary content table. Populated from MOR Directive 17/2011 documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-sectors".
 */
export interface BusinessSector {
  id: number;
  /**
   * Official MOR sector code as it appears in Directive 17/2011.
   */
  mor_code: string;
  name_en: string;
  name_am?: string | null;
  slug: string;
  category: number | SectorCategory;
  description_short: string;
  description_full?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Previous codes that map to this sector under Directive 17/2011.
   */
  legacy_codes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  permitted_operations_am?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  permitted_operations_en?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  is_featured?: boolean | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-categories".
 */
export interface SectorCategory {
  id: number;
  name_en: string;
  name_am?: string | null;
  /**
   * URL-safe slug (lowercase, dashes).
   */
  slug: string;
  /**
   * Lucide icon name or emoji.
   */
  icon?: string | null;
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-license-requirements".
 */
export interface SectorLicenseRequirement {
  id: number;
  sector: number | BusinessSector;
  license_type: string;
  issuing_authority: string;
  is_required?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-competency-certificates".
 */
export interface SectorCompetencyCertificate {
  id: number;
  sector: number | BusinessSector;
  certificate_name: string;
  issuing_body: string;
  is_mandatory?: boolean | null;
  description?: string | null;
  processing_days_min?: number | null;
  processing_days_max?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-approvals".
 */
export interface SectorApproval {
  id: number;
  sector: number | BusinessSector;
  approval_name: string;
  approving_ministry: string;
  sequence_order: number;
  processing_days_min?: number | null;
  processing_days_max?: number | null;
  is_required?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-costs".
 */
export interface SectorCost {
  id: number;
  sector: number | BusinessSector;
  cost_item: string;
  amount_birr_min?: number | null;
  amount_birr_max?: number | null;
  amount_usd_min?: number | null;
  amount_usd_max?: number | null;
  /**
   * True = government fee. False = our estimate.
   */
  is_official_fee?: boolean | null;
  notes?: string | null;
  last_verified_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-steps".
 */
export interface SectorStep {
  id: number;
  sector: number | BusinessSector;
  step_number: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Physical office or URL (e.g. Bishoftu City Trade Office).
   */
  where_to_go?: string | null;
  documents_needed?:
    | {
        document: string;
        id?: string | null;
      }[]
    | null;
  estimated_days?: number | null;
  cost_reference?: (number | null) | SectorCost;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-documents".
 */
export interface SectorDocument {
  id: number;
  sector: number | BusinessSector;
  title: string;
  description?: string | null;
  file_type: 'pdf' | 'docx' | 'xlsx';
  download_count?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  title: string;
  slug: string;
  description: string;
  /**
   * Optional — leave blank for cross-sector reports.
   */
  sector?: (number | null) | BusinessSector;
  price_usd: number;
  price_birr: number;
  /**
   * Public preview PDF (first few pages).
   */
  preview?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility and SEO.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts".
 */
export interface Expert {
  id: number;
  full_name: string;
  /**
   * e.g. Business Registration Agent
   */
  title: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specializations?:
    | {
        sector?: (number | null) | BusinessSector;
        free_text?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        code: 'am' | 'en' | 'or' | 'ti' | 'so';
        id?: string | null;
      }[]
    | null;
  location?: string | null;
  is_platform_team?: boolean | null;
  is_verified?: boolean | null;
  /**
   * Computed from expert_reviews.
   */
  rating_avg?: number | null;
  review_count?: number | null;
  session_price_usd: number;
  session_price_birr: number;
  /**
   * Cal.com username for booking proxy.
   */
  cal_username?: string | null;
  profile_image?: (number | null) | Media;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-research".
 */
export interface MarketResearch {
  id: number;
  title: string;
  city: string;
  category: 'demographics' | 'tourism' | 'economy' | 'infrastructure' | 'opportunities' | 'other';
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  structured_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source?: string | null;
  collected_at: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  seo_description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover_image?: (number | null) | Media;
  sector?: (number | null) | BusinessSector;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  published_at?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-sectors".
 */
export interface SavedSector {
  id: number;
  user_id: string;
  sector: number | BusinessSector;
  saved_at: string;
  /**
   * Optional 200-char note the user attached to this bookmark.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-reports".
 */
export interface SavedReport {
  id: number;
  user_id: string;
  report: number | Report;
  saved_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-checklists".
 */
export interface UserChecklist {
  id: number;
  user_id: string;
  sector: number | BusinessSector;
  /**
   * One row per checklist item this user is tracking.
   */
  items?:
    | {
        step_id: string;
        completed?: boolean | null;
        completed_at?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-computed from items[].completed.
   */
  progress_pct?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-requests".
 */
export interface ReportRequest {
  id: number;
  user_id: string;
  /**
   * catalog = user picked from /dashboard/reports; custom = user described a document we don't stock (MOR fee schedule, Trade Bureau circular, etc.) and we fulfill manually.
   */
  request_type: 'catalog' | 'custom';
  report?: (number | null) | Report;
  /**
   * Short name of the document the user wants (e.g. "MOR Directive 17/2011 fee schedule").
   */
  custom_title?: string | null;
  custom_source?: ('mor' | 'motri' | 'trade_bureau' | 'eic' | 'nbe' | 'customs' | 'csa' | 'other_gov' | 'other') | null;
  /**
   * Any extra context — dates, sector codes, why they need it.
   */
  custom_notes?: string | null;
  amount_etb: number;
  amount_usd?: number | null;
  payment_method: 'telebirr' | 'cbe_birr';
  /**
   * Transaction reference number user provided.
   */
  payment_reference?: string | null;
  /**
   * Screenshot proof of the payment; PNG / JPEG / WebP up to 5MB.
   */
  payment_screenshot: number | Media;
  status: 'pending' | 'verified' | 'rejected';
  /**
   * Visible to the user on their /dashboard/requests page.
   */
  admin_note?: string | null;
  verified_by?: (number | null) | Admin;
  verified_at?: string | null;
  /**
   * Set to +30 days when status flips to verified.
   */
  download_expires_at?: string | null;
  /**
   * Incremented on every successful download.
   */
  download_count?: number | null;
  /**
   * For custom requests: the PDF/asset the admin procured (from MOR, Trade Bureau, etc.) and uploaded. Users hit /api/downloads/<id> to fetch it once status = verified.
   */
  fulfilled_asset?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-sources".
 */
export interface NewsSource {
  id: number;
  name: string;
  type: 'news_site' | 'newspaper' | 'tv' | 'youtube' | 'telegram' | 'gov_portal' | 'economic_data';
  url: string;
  /**
   * Telegram/YouTube handle without @ (e.g. tebekasamuel).
   */
  handle?: string | null;
  category?: ('business' | 'policy' | 'finance' | 'sector_specific' | 'general') | null;
  /**
   * Optional — tie a Telegram channel to a specific MOR sector.
   */
  sector_hint?: (number | null) | BusinessSector;
  logo?: (number | null) | Media;
  description_en?: string | null;
  description_am?: string | null;
  /**
   * Higher = shown earlier in the feed.
   */
  priority?: number | null;
  is_active?: boolean | null;
  /**
   * Telegram only. If on, /dashboard/pulse will pull recent post previews from t.me/s/<handle> and cache for 30 min.
   */
  allow_scrape?: boolean | null;
  /**
   * Optional metadata for display.
   */
  subscribers?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning-canvases".
 */
export interface PlanningCanvase {
  id: number;
  user_id: string;
  title: string;
  template?: ('blank' | 'onboarding') | null;
  /**
   * React Flow node array — [{ id, type, position: {x,y}, data: {...} }].
   */
  nodes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * React Flow edge array — [{ id, source, target, label? }].
   */
  edges:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When true, anyone with the share_token can view (read-only).
   */
  is_public?: boolean | null;
  /**
   * Auto-generated on first publish.
   */
  share_token?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'business-sectors';
        value: number | BusinessSector;
      } | null)
    | ({
        relationTo: 'sector-categories';
        value: number | SectorCategory;
      } | null)
    | ({
        relationTo: 'sector-license-requirements';
        value: number | SectorLicenseRequirement;
      } | null)
    | ({
        relationTo: 'sector-competency-certificates';
        value: number | SectorCompetencyCertificate;
      } | null)
    | ({
        relationTo: 'sector-approvals';
        value: number | SectorApproval;
      } | null)
    | ({
        relationTo: 'sector-costs';
        value: number | SectorCost;
      } | null)
    | ({
        relationTo: 'sector-steps';
        value: number | SectorStep;
      } | null)
    | ({
        relationTo: 'sector-documents';
        value: number | SectorDocument;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'experts';
        value: number | Expert;
      } | null)
    | ({
        relationTo: 'market-research';
        value: number | MarketResearch;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'saved-sectors';
        value: number | SavedSector;
      } | null)
    | ({
        relationTo: 'saved-reports';
        value: number | SavedReport;
      } | null)
    | ({
        relationTo: 'user-checklists';
        value: number | UserChecklist;
      } | null)
    | ({
        relationTo: 'report-requests';
        value: number | ReportRequest;
      } | null)
    | ({
        relationTo: 'news-sources';
        value: number | NewsSource;
      } | null)
    | ({
        relationTo: 'planning-canvases';
        value: number | PlanningCanvase;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-sectors_select".
 */
export interface BusinessSectorsSelect<T extends boolean = true> {
  mor_code?: T;
  name_en?: T;
  name_am?: T;
  slug?: T;
  category?: T;
  description_short?: T;
  description_full?: T;
  legacy_codes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  permitted_operations_am?:
    | T
    | {
        text?: T;
        id?: T;
      };
  permitted_operations_en?:
    | T
    | {
        text?: T;
        id?: T;
      };
  is_featured?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-categories_select".
 */
export interface SectorCategoriesSelect<T extends boolean = true> {
  name_en?: T;
  name_am?: T;
  slug?: T;
  icon?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-license-requirements_select".
 */
export interface SectorLicenseRequirementsSelect<T extends boolean = true> {
  sector?: T;
  license_type?: T;
  issuing_authority?: T;
  is_required?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-competency-certificates_select".
 */
export interface SectorCompetencyCertificatesSelect<T extends boolean = true> {
  sector?: T;
  certificate_name?: T;
  issuing_body?: T;
  is_mandatory?: T;
  description?: T;
  processing_days_min?: T;
  processing_days_max?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-approvals_select".
 */
export interface SectorApprovalsSelect<T extends boolean = true> {
  sector?: T;
  approval_name?: T;
  approving_ministry?: T;
  sequence_order?: T;
  processing_days_min?: T;
  processing_days_max?: T;
  is_required?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-costs_select".
 */
export interface SectorCostsSelect<T extends boolean = true> {
  sector?: T;
  cost_item?: T;
  amount_birr_min?: T;
  amount_birr_max?: T;
  amount_usd_min?: T;
  amount_usd_max?: T;
  is_official_fee?: T;
  notes?: T;
  last_verified_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-steps_select".
 */
export interface SectorStepsSelect<T extends boolean = true> {
  sector?: T;
  step_number?: T;
  title?: T;
  description?: T;
  where_to_go?: T;
  documents_needed?:
    | T
    | {
        document?: T;
        id?: T;
      };
  estimated_days?: T;
  cost_reference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-documents_select".
 */
export interface SectorDocumentsSelect<T extends boolean = true> {
  sector?: T;
  title?: T;
  description?: T;
  file_type?: T;
  download_count?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sector?: T;
  price_usd?: T;
  price_birr?: T;
  preview?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts_select".
 */
export interface ExpertsSelect<T extends boolean = true> {
  full_name?: T;
  title?: T;
  bio?: T;
  specializations?:
    | T
    | {
        sector?: T;
        free_text?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        code?: T;
        id?: T;
      };
  location?: T;
  is_platform_team?: T;
  is_verified?: T;
  rating_avg?: T;
  review_count?: T;
  session_price_usd?: T;
  session_price_birr?: T;
  cal_username?: T;
  profile_image?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-research_select".
 */
export interface MarketResearchSelect<T extends boolean = true> {
  title?: T;
  city?: T;
  category?: T;
  content?: T;
  structured_data?: T;
  source?: T;
  collected_at?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo_description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  cover_image?: T;
  sector?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  published_at?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-sectors_select".
 */
export interface SavedSectorsSelect<T extends boolean = true> {
  user_id?: T;
  sector?: T;
  saved_at?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-reports_select".
 */
export interface SavedReportsSelect<T extends boolean = true> {
  user_id?: T;
  report?: T;
  saved_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-checklists_select".
 */
export interface UserChecklistsSelect<T extends boolean = true> {
  user_id?: T;
  sector?: T;
  items?:
    | T
    | {
        step_id?: T;
        completed?: T;
        completed_at?: T;
        note?: T;
        id?: T;
      };
  progress_pct?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-requests_select".
 */
export interface ReportRequestsSelect<T extends boolean = true> {
  user_id?: T;
  request_type?: T;
  report?: T;
  custom_title?: T;
  custom_source?: T;
  custom_notes?: T;
  amount_etb?: T;
  amount_usd?: T;
  payment_method?: T;
  payment_reference?: T;
  payment_screenshot?: T;
  status?: T;
  admin_note?: T;
  verified_by?: T;
  verified_at?: T;
  download_expires_at?: T;
  download_count?: T;
  fulfilled_asset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-sources_select".
 */
export interface NewsSourcesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  url?: T;
  handle?: T;
  category?: T;
  sector_hint?: T;
  logo?: T;
  description_en?: T;
  description_am?: T;
  priority?: T;
  is_active?: T;
  allow_scrape?: T;
  subscribers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning-canvases_select".
 */
export interface PlanningCanvasesSelect<T extends boolean = true> {
  user_id?: T;
  title?: T;
  template?: T;
  nodes?: T;
  edges?: T;
  is_public?: T;
  share_token?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  site_name: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  social_links?: {
    twitter?: string | null;
    linkedin?: string | null;
    telegram?: string | null;
    whatsapp?: string | null;
  };
  support_email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content".
 */
export interface HomepageContent {
  id: number;
  hero: {
    eyebrow?: string | null;
    headline: string;
    subhead?: string | null;
    primary_cta_label?: string | null;
    primary_cta_href?: string | null;
    secondary_cta_label?: string | null;
    secondary_cta_href?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  site_name?: T;
  tagline?: T;
  logo?: T;
  social_links?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        telegram?: T;
        whatsapp?: T;
      };
  support_email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
        primary_cta_label?: T;
        primary_cta_href?: T;
        secondary_cta_label?: T;
        secondary_cta_href?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}